/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type BannerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "banner";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  bannerSlotA?: BannerReference;
  bannerSlotB?: BannerReference;
  bannerSlotC?: BannerReference;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Banner = {
  _id: string;
  _type: "banner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  href?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ArticleImage = {
  _type: "articleImage";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  fullBleed?: boolean;
};

export type HtmlTable = {
  _type: "htmlTable";
  html?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type FileAttachment = {
  _type: "fileAttachment";
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  label?: string;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  dateStart?: string;
  dateEnd?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  externalLink?: {
    url?: string;
    label?: string;
  };
  featuredOnHome?: boolean;
};

export type Sponsor = {
  _id: string;
  _type: "sponsor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url?: string;
  tier?: "hoofdsponsor" | "sponsor" | "sympathisant";
  featured?: boolean;
  type?: "crossing" | "training" | "white" | "green" | "panel" | "other";
  active?: boolean;
};

export type PlayerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "player";
};

export type StaffMemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "staffMember";
};

export type TeamReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "team";
};

export type ArticleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "article";
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishAt?: string;
  unpublishAt?: string;
  featured?: boolean;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  tags?: Array<string>;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
          | {
              reference?:
                | PlayerReference
                | StaffMemberReference
                | TeamReference
                | ArticleReference
                | PageReference;
              _type: "internalLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & ArticleImage)
    | ({
        _key: string;
      } & FileAttachment)
    | ({
        _key: string;
      } & HtmlTable)
  >;
  relatedArticles?: Array<
    {
      _key: string;
    } & ArticleReference
  >;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & FileAttachment)
  >;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type ResponsibilityPathReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "responsibilityPath";
};

export type ResponsibilityPath = {
  _id: string;
  _type: "responsibilityPath";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  active?: boolean;
  audience?: Array<
    "speler" | "ouder" | "trainer" | "supporter" | "niet-lid" | "andere"
  >;
  question?: string;
  keywords?: Array<string>;
  summary?: string;
  category?:
    | "medisch"
    | "sportief"
    | "administratief"
    | "gedrag"
    | "algemeen"
    | "commercieel";
  icon?: string;
  primaryContact?: {
    staffMember?: StaffMemberReference;
    role?: string;
    email?: string;
    phone?: string;
    department?: "hoofdbestuur" | "jeugdbestuur" | "algemeen";
  };
  steps?: Array<{
    description?: string;
    link?: string;
    contact?: {
      staffMember?: StaffMemberReference;
      role?: string;
      email?: string;
      phone?: string;
      department?: "hoofdbestuur" | "jeugdbestuur" | "algemeen";
    };
    _type: "solutionStep";
    _key: string;
  }>;
  relatedPaths?: Array<
    {
      _key: string;
    } & ResponsibilityPathReference
  >;
};

export type StaffMember = {
  _id: string;
  _type: "staffMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName?: string;
  lastName?: string;
  role?:
    | "hoofdtrainer"
    | "assistent"
    | "keeperstrainer"
    | "tvjo"
    | "ploegdelegatie"
    | "afgevaardigde"
    | "coach"
    | "voorzitter"
    | "ondervoorzitter"
    | "secretaris"
    | "penningmeester"
    | "jeugdcoordinator"
    | "jeugdsecretaris"
    | "technisch-coordinator"
    | "sportief-verantwoordelijke"
    | "sponsoring-verantwoordelijke"
    | "verzekering-verantwoordelijke"
    | "evenementen-coordinator"
    | "pr-verantwoordelijke"
    | "kantine-verantwoordelijke"
    | "webmaster"
    | "bestuur"
    | "other";
  department?: "hoofdbestuur" | "jeugdbestuur" | "algemeen";
  email?: string;
  phone?: string;
  birthDate?: string;
  joinDate?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  inOrganigram?: boolean;
  parentMember?: StaffMemberReference;
  positionTitle?: string;
  positionShort?: string;
  responsibilities?: string;
  psdId?: string;
  archived?: boolean;
};

export type TrainingSession = {
  _type: "trainingSession";
  day?:
    | "Maandag"
    | "Dinsdag"
    | "Woensdag"
    | "Donderdag"
    | "Vrijdag"
    | "Zaterdag"
    | "Zondag";
  time?: string;
  location?: string;
  type?: "Training" | "Fysiek" | "Tactisch" | "Keeperstraining" | "Andere";
};

export type Team = {
  _id: string;
  _type: "team";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  psdId?: string;
  name?: string;
  slug?: Slug;
  age?: string;
  gender?: string;
  footbelId?: number;
  leagueId?: number;
  league?: string;
  division?: string;
  divisionFull?: string;
  season?: string;
  players?: Array<
    {
      _key: string;
    } & PlayerReference
  >;
  showInNavigation?: boolean;
  tagline?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  contactInfo?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  teamImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  trainingSchedule?: Array<
    {
      _key: string;
    } & TrainingSession
  >;
  staff?: Array<
    {
      _key: string;
    } & StaffMemberReference
  >;
  archived?: boolean;
};

export type Player = {
  _id: string;
  _type: "player";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  psdId?: string;
  firstName?: string;
  lastName?: string;
  birthDate?: string;
  nationality?: string;
  keeper?: boolean;
  positionPsd?: string;
  archived?: boolean;
  jerseyNumber?: number;
  height?: number;
  weight?: number;
  psdImageUrl?: string;
  psdImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  transparentImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  celebrationImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  position?: "Keeper" | "Verdediger" | "Middenvelder" | "Aanvaller" | "Speler";
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | BannerReference
  | HomePage
  | SanityImageAssetReference
  | Banner
  | SanityImageCrop
  | SanityImageHotspot
  | ArticleImage
  | HtmlTable
  | SanityFileAssetReference
  | FileAttachment
  | Event
  | Sponsor
  | PlayerReference
  | StaffMemberReference
  | TeamReference
  | ArticleReference
  | PageReference
  | Article
  | Page
  | Slug
  | ResponsibilityPathReference
  | ResponsibilityPath
  | StaffMember
  | TrainingSession
  | Team
  | Player
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/lib/sanity/queries/articles.ts
// Variable: ARTICLES_QUERY
// Query: *[_type == "article" && publishAt <= now() && (!defined(unpublishAt) || unpublishAt > now())] | order(publishAt desc) {  _id, title, slug, publishAt, featured, tags,  "coverImageUrl": coverImage.asset->url + "?w=1200&q=80&fm=webp&fit=max",  body[]{ ..., "fileUrl": file.asset->url, "fileSize": file.asset->size, "fileMimeType": file.asset->mimeType, "fileOriginalFilename": file.asset->originalFilename, "asset": select(_type == "image" => asset->{ "url": url + "?w=800&q=80&fm=webp&fit=max" }, _type == "articleImage" => image.asset->{ "url": url + "?w=800&q=80&fm=webp&fit=max" }), markDefs[]{ ..., _type == "internalLink" => { ..., "reference": reference->{ _type, "slug": slug.current, psdId } } } }}
export type ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishAt: string | null;
  featured: boolean | null;
  tags: Array<string> | null;
  coverImageUrl: string | null;
  body: Array<
    | {
        _key: string;
        _type: "articleImage";
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        alt?: string;
        fullBleed?: boolean;
        fileUrl: null;
        fileSize: null;
        fileMimeType: null;
        fileOriginalFilename: null;
        asset: {
          url: string | null;
        } | null;
        markDefs: null;
      }
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              reference:
                | {
                    _type: "article";
                    slug: string | null;
                    psdId: null;
                  }
                | {
                    _type: "page";
                    slug: string | null;
                    psdId: null;
                  }
                | {
                    _type: "player";
                    slug: null;
                    psdId: string | null;
                  }
                | {
                    _type: "staffMember";
                    slug: null;
                    psdId: string | null;
                  }
                | {
                    _type: "team";
                    slug: string | null;
                    psdId: string | null;
                  }
                | null;
              _type: "internalLink";
              _key: string;
            }
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
        fileUrl: null;
        fileSize: null;
        fileMimeType: null;
        fileOriginalFilename: null;
        asset: null;
      }
    | {
        _key: string;
        _type: "fileAttachment";
        file?: {
          asset?: SanityFileAssetReference;
          media?: unknown;
          _type: "file";
        };
        label?: string;
        fileUrl: string | null;
        fileSize: number | null;
        fileMimeType: string | null;
        fileOriginalFilename: string | null;
        asset: null;
        markDefs: null;
      }
    | {
        _key: string;
        _type: "htmlTable";
        html?: string;
        fileUrl: null;
        fileSize: null;
        fileMimeType: null;
        fileOriginalFilename: null;
        asset: null;
        markDefs: null;
      }
  > | null;
}>;

// Source: ../web/src/lib/sanity/queries/articles.ts
// Variable: ARTICLE_TAGS_QUERY
// Query: array::unique(*[_type == "article" && publishAt <= now() && (!defined(unpublishAt) || unpublishAt > now())].tags[])
export type ARTICLE_TAGS_QUERY_RESULT = Array<string | null>;

// Source: ../web/src/lib/sanity/queries/articles.ts
// Variable: RELATED_ARTICLES_QUERY
// Query: *[_type == "article" && references($documentId) && publishAt <= now() && (!defined(unpublishAt) || unpublishAt > now())] | order(publishAt desc) {  _id, title, slug, publishAt, featured, tags,  "coverImageUrl": coverImage.asset->url + "?w=800&q=80&fm=webp&fit=max"}
export type RELATED_ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishAt: string | null;
  featured: boolean | null;
  tags: Array<string> | null;
  coverImageUrl: string | null;
}>;

// Source: ../web/src/lib/sanity/queries/articles.ts
// Variable: ARTICLE_BY_SLUG_QUERY
// Query: *[_type == "article" && slug.current == $slug && publishAt <= now() && (!defined(unpublishAt) || unpublishAt > now())][0] {  _id, title, slug, publishAt, featured, tags,  "coverImageUrl": coverImage.asset->url + "?w=1200&q=80&fm=webp&fit=max",  body[]{ ..., "fileUrl": file.asset->url, "fileSize": file.asset->size, "fileMimeType": file.asset->mimeType, "fileOriginalFilename": file.asset->originalFilename, "asset": select(_type == "image" => asset->{ "url": url + "?w=800&q=80&fm=webp&fit=max" }, _type == "articleImage" => image.asset->{ "url": url + "?w=800&q=80&fm=webp&fit=max" }), markDefs[]{ ..., _type == "internalLink" => { ..., "reference": reference->{ _type, "slug": slug.current, psdId } } } },  relatedArticles[]-> { _id, title, slug, publishAt, unpublishAt, "coverImageUrl": coverImage.asset->url + "?w=800&q=80&fm=webp&fit=max" },  "mentionedPlayers": body[].markDefs[_type == "internalLink" && reference->_type == "player"].reference-> {    _id, firstName, lastName, position,    "imageUrl": psdImage.asset->url + "?w=400&q=80&fm=webp&fit=max",    psdId  },  "mentionedTeams": body[].markDefs[_type == "internalLink" && reference->_type == "team"].reference-> {    _id, name,    "imageUrl": teamImage.asset->url + "?w=400&q=80&fm=webp&fit=max",    "slug": slug.current  },  "mentionedStaffMembers": body[].markDefs[_type == "internalLink" && reference->_type == "staffMember"].reference-> {    _id, firstName, lastName, positionTitle,    "imageUrl": photo.asset->url + "?w=400&q=80&fm=webp&fit=max"  }}
export type ARTICLE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishAt: string | null;
  featured: boolean | null;
  tags: Array<string> | null;
  coverImageUrl: string | null;
  body: Array<
    | {
        _key: string;
        _type: "articleImage";
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        alt?: string;
        fullBleed?: boolean;
        fileUrl: null;
        fileSize: null;
        fileMimeType: null;
        fileOriginalFilename: null;
        asset: {
          url: string | null;
        } | null;
        markDefs: null;
      }
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              reference:
                | {
                    _type: "article";
                    slug: string | null;
                    psdId: null;
                  }
                | {
                    _type: "page";
                    slug: string | null;
                    psdId: null;
                  }
                | {
                    _type: "player";
                    slug: null;
                    psdId: string | null;
                  }
                | {
                    _type: "staffMember";
                    slug: null;
                    psdId: string | null;
                  }
                | {
                    _type: "team";
                    slug: string | null;
                    psdId: string | null;
                  }
                | null;
              _type: "internalLink";
              _key: string;
            }
          | {
              href?: string;
              _type: "link";
              _key: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
        fileUrl: null;
        fileSize: null;
        fileMimeType: null;
        fileOriginalFilename: null;
        asset: null;
      }
    | {
        _key: string;
        _type: "fileAttachment";
        file?: {
          asset?: SanityFileAssetReference;
          media?: unknown;
          _type: "file";
        };
        label?: string;
        fileUrl: string | null;
        fileSize: number | null;
        fileMimeType: string | null;
        fileOriginalFilename: string | null;
        asset: null;
        markDefs: null;
      }
    | {
        _key: string;
        _type: "htmlTable";
        html?: string;
        fileUrl: null;
        fileSize: null;
        fileMimeType: null;
        fileOriginalFilename: null;
        asset: null;
        markDefs: null;
      }
  > | null;
  relatedArticles: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    publishAt: string | null;
    unpublishAt: string | null;
    coverImageUrl: string | null;
  }> | null;
  mentionedPlayers: Array<
    | {
        _id: string;
        firstName: null;
        lastName: null;
        position: null;
        imageUrl: null;
        psdId: null;
      }
    | {
        _id: string;
        firstName: null;
        lastName: null;
        position: null;
        imageUrl: null;
        psdId: string | null;
      }
    | {
        _id: string;
        firstName: string | null;
        lastName: string | null;
        position: null;
        imageUrl: null;
        psdId: string | null;
      }
    | {
        _id: string;
        firstName: string | null;
        lastName: string | null;
        position:
          | "Aanvaller"
          | "Keeper"
          | "Middenvelder"
          | "Speler"
          | "Verdediger"
          | null;
        imageUrl: string | null;
        psdId: string | null;
      }
    | null
  > | null;
  mentionedTeams: Array<
    | {
        _id: string;
        name: null;
        imageUrl: null;
        slug: null;
      }
    | {
        _id: string;
        name: null;
        imageUrl: null;
        slug: string | null;
      }
    | {
        _id: string;
        name: string | null;
        imageUrl: string | null;
        slug: string | null;
      }
    | null
  > | null;
  mentionedStaffMembers: Array<
    | {
        _id: string;
        firstName: null;
        lastName: null;
        positionTitle: null;
        imageUrl: null;
      }
    | {
        _id: string;
        firstName: string | null;
        lastName: string | null;
        positionTitle: null;
        imageUrl: null;
      }
    | {
        _id: string;
        firstName: string | null;
        lastName: string | null;
        positionTitle: string | null;
        imageUrl: string | null;
      }
    | null
  > | null;
} | null;

// Source: ../web/src/lib/sanity/queries/homePage.ts
// Variable: HOMEPAGE_BANNERS_QUERY
// Query: *[_type == "homePage"][0] {    "bannerSlotA": bannerSlotA-> {      _id,      "imageUrl": image.asset->url,      alt,      href    },    "bannerSlotB": bannerSlotB-> {      _id,      "imageUrl": image.asset->url,      alt,      href    },    "bannerSlotC": bannerSlotC-> {      _id,      "imageUrl": image.asset->url,      alt,      href    }  }
export type HOMEPAGE_BANNERS_QUERY_RESULT = {
  bannerSlotA: {
    _id: string;
    imageUrl: string | null;
    alt: string | null;
    href: string | null;
  } | null;
  bannerSlotB: {
    _id: string;
    imageUrl: string | null;
    alt: string | null;
    href: string | null;
  } | null;
  bannerSlotC: {
    _id: string;
    imageUrl: string | null;
    alt: string | null;
    href: string | null;
  } | null;
} | null;

// Source: ../web/src/lib/sanity/queries/players.ts
// Variable: PLAYERS_QUERY
// Query: *[_type == "player" && archived != true] | order(lastName asc) {  _id, psdId, firstName, lastName, jerseyNumber, keeper, positionPsd, position,  birthDate, nationality, height, weight,  "psdImageUrl": psdImage.asset->url + "?w=400&q=80&fm=webp&fit=max",  "transparentImageUrl": transparentImage.asset->url + "?w=600&q=80&fm=webp&fit=max",  "celebrationImageUrl": celebrationImage.asset->url + "?w=600&q=80&fm=webp&fit=max",  bio}
export type PLAYERS_QUERY_RESULT = Array<{
  _id: string;
  psdId: string | null;
  firstName: string | null;
  lastName: string | null;
  jerseyNumber: number | null;
  keeper: boolean | null;
  positionPsd: string | null;
  position:
    | "Aanvaller"
    | "Keeper"
    | "Middenvelder"
    | "Speler"
    | "Verdediger"
    | null;
  birthDate: string | null;
  nationality: string | null;
  height: number | null;
  weight: number | null;
  psdImageUrl: string | null;
  transparentImageUrl: string | null;
  celebrationImageUrl: string | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
}>;

// Source: ../web/src/lib/sanity/queries/players.ts
// Variable: PLAYER_BY_PSD_ID_QUERY
// Query: *[_type == "player" && psdId == $psdId][0] {  _id, psdId, firstName, lastName, jerseyNumber, keeper, positionPsd, position,  birthDate, nationality, height, weight,  "psdImageUrl": psdImage.asset->url + "?w=400&q=80&fm=webp&fit=max",  "transparentImageUrl": transparentImage.asset->url + "?w=600&q=80&fm=webp&fit=max",  "celebrationImageUrl": celebrationImage.asset->url + "?w=600&q=80&fm=webp&fit=max",  bio}
export type PLAYER_BY_PSD_ID_QUERY_RESULT = {
  _id: string;
  psdId: string | null;
  firstName: string | null;
  lastName: string | null;
  jerseyNumber: number | null;
  keeper: boolean | null;
  positionPsd: string | null;
  position:
    | "Aanvaller"
    | "Keeper"
    | "Middenvelder"
    | "Speler"
    | "Verdediger"
    | null;
  birthDate: string | null;
  nationality: string | null;
  height: number | null;
  weight: number | null;
  psdImageUrl: string | null;
  transparentImageUrl: string | null;
  celebrationImageUrl: string | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: ../web/src/lib/sanity/queries/sponsors.ts
// Variable: SPONSORS_QUERY
// Query: *[_type == "sponsor" && active == true] | order(name asc) {  _id, name, url, type, tier, featured, "logoUrl": logo.asset->url + "?w=400&q=80&fm=webp&fit=max"}
export type SPONSORS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  url: string | null;
  type: "crossing" | "green" | "other" | "panel" | "training" | "white" | null;
  tier: "hoofdsponsor" | "sponsor" | "sympathisant" | null;
  featured: boolean | null;
  logoUrl: string | null;
}>;

// Source: ../web/src/lib/sanity/queries/staffMembers.ts
// Variable: STAFF_MEMBERS_QUERY
// Query: *[_type == "staffMember" && archived != true && inOrganigram == true] | order(lastName asc) {  _id,  firstName,  lastName,  positionTitle,  positionShort,  department,  email,  phone,  "photoUrl": photo.asset->url + "?w=200&q=80&fm=webp&fit=max",  responsibilities,  "parentId": select(defined(parentMember) && parentMember->inOrganigram == true && parentMember->archived != true => parentMember->_id, null)}
export type STAFF_MEMBERS_QUERY_RESULT = Array<{
  _id: string;
  firstName: string | null;
  lastName: string | null;
  positionTitle: string | null;
  positionShort: string | null;
  department: "algemeen" | "hoofdbestuur" | "jeugdbestuur" | null;
  email: string | null;
  phone: string | null;
  photoUrl: string | null;
  responsibilities: string | null;
  parentId: string | null;
}>;

// Source: ../web/src/lib/sanity/queries/teams.ts
// Variable: TEAMS_QUERY
// Query: *[_type == "team" && archived != true && showInNavigation != false] | order(name asc) {  _id, psdId, name, "slug": slug.current, age, gender, footbelId, leagueId, division, divisionFull,  tagline,  "teamImageUrl": teamImage.asset->url + "?w=1200&q=80&fm=webp&fit=max"}
export type TEAMS_QUERY_RESULT = Array<{
  _id: string;
  psdId: string | null;
  name: string | null;
  slug: string | null;
  age: string | null;
  gender: string | null;
  footbelId: number | null;
  leagueId: number | null;
  division: string | null;
  divisionFull: string | null;
  tagline: string | null;
  teamImageUrl: string | null;
}>;

// Source: ../web/src/lib/sanity/queries/teams.ts
// Variable: TEAM_BY_SLUG_QUERY
// Query: *[_type == "team" && slug.current == $slug][0] {  _id, psdId, name, "slug": slug.current, age, gender, footbelId, leagueId, division, divisionFull,  tagline, body[]{ ..., "fileUrl": file.asset->url }, contactInfo,  "teamImageUrl": teamImage.asset->url + "?w=1200&q=80&fm=webp&fit=max",  trainingSchedule,  players[]-> {    _id, psdId, firstName, lastName, jerseyNumber, keeper, positionPsd, position,    "psdImageUrl": psdImage.asset->url + "?w=400&q=80&fm=webp&fit=max",    "transparentImageUrl": transparentImage.asset->url + "?w=600&q=80&fm=webp&fit=max"  },  staff[]-> { _id, firstName, lastName, role, "photoUrl": photo.asset->url + "?w=200&q=80&fm=webp&fit=max" }}
export type TEAM_BY_SLUG_QUERY_RESULT = {
  _id: string;
  psdId: string | null;
  name: string | null;
  slug: string | null;
  age: string | null;
  gender: string | null;
  footbelId: number | null;
  leagueId: number | null;
  division: string | null;
  divisionFull: string | null;
  tagline: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
    fileUrl: null;
  }> | null;
  contactInfo: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  teamImageUrl: string | null;
  trainingSchedule: Array<
    {
      _key: string;
    } & TrainingSession
  > | null;
  players: Array<{
    _id: string;
    psdId: string | null;
    firstName: string | null;
    lastName: string | null;
    jerseyNumber: number | null;
    keeper: boolean | null;
    positionPsd: string | null;
    position:
      | "Aanvaller"
      | "Keeper"
      | "Middenvelder"
      | "Speler"
      | "Verdediger"
      | null;
    psdImageUrl: string | null;
    transparentImageUrl: string | null;
  }> | null;
  staff: Array<{
    _id: string;
    firstName: string | null;
    lastName: string | null;
    role:
      | "afgevaardigde"
      | "assistent"
      | "bestuur"
      | "coach"
      | "evenementen-coordinator"
      | "hoofdtrainer"
      | "jeugdcoordinator"
      | "jeugdsecretaris"
      | "kantine-verantwoordelijke"
      | "keeperstrainer"
      | "ondervoorzitter"
      | "other"
      | "penningmeester"
      | "ploegdelegatie"
      | "pr-verantwoordelijke"
      | "secretaris"
      | "sponsoring-verantwoordelijke"
      | "sportief-verantwoordelijke"
      | "technisch-coordinator"
      | "tvjo"
      | "verzekering-verantwoordelijke"
      | "voorzitter"
      | "webmaster"
      | null;
    photoUrl: string | null;
  }> | null;
} | null;

// Source: ../web/src/lib/sanity/queries/teams.ts
// Variable: TEAMS_LANDING_QUERY
// Query: *[_type == "team" && archived != true && showInNavigation != false && defined(age)] | order(name asc) {  _id, name, "slug": slug.current, age,  division, divisionFull, tagline,  "teamImageUrl": teamImage.asset->url + "?w=1200&q=80&fm=webp&fit=max",  staff[]-> { firstName, lastName, role }}
export type TEAMS_LANDING_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  age: string | null;
  division: string | null;
  divisionFull: string | null;
  tagline: string | null;
  teamImageUrl: string | null;
  staff: Array<{
    firstName: string | null;
    lastName: string | null;
    role:
      | "afgevaardigde"
      | "assistent"
      | "bestuur"
      | "coach"
      | "evenementen-coordinator"
      | "hoofdtrainer"
      | "jeugdcoordinator"
      | "jeugdsecretaris"
      | "kantine-verantwoordelijke"
      | "keeperstrainer"
      | "ondervoorzitter"
      | "other"
      | "penningmeester"
      | "ploegdelegatie"
      | "pr-verantwoordelijke"
      | "secretaris"
      | "sponsoring-verantwoordelijke"
      | "sportief-verantwoordelijke"
      | "technisch-coordinator"
      | "tvjo"
      | "verzekering-verantwoordelijke"
      | "voorzitter"
      | "webmaster"
      | null;
  }> | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "article" && publishAt <= now() && (!defined(unpublishAt) || unpublishAt > now())] | order(publishAt desc) {\n  _id, title, slug, publishAt, featured, tags,\n  "coverImageUrl": coverImage.asset->url + "?w=1200&q=80&fm=webp&fit=max",\n  body[]{ ..., "fileUrl": file.asset->url, "fileSize": file.asset->size, "fileMimeType": file.asset->mimeType, "fileOriginalFilename": file.asset->originalFilename, "asset": select(_type == "image" => asset->{ "url": url + "?w=800&q=80&fm=webp&fit=max" }, _type == "articleImage" => image.asset->{ "url": url + "?w=800&q=80&fm=webp&fit=max" }), markDefs[]{ ..., _type == "internalLink" => { ..., "reference": reference->{ _type, "slug": slug.current, psdId } } } }\n}': ARTICLES_QUERY_RESULT;
    'array::unique(*[_type == "article" && publishAt <= now() && (!defined(unpublishAt) || unpublishAt > now())].tags[])': ARTICLE_TAGS_QUERY_RESULT;
    '*[_type == "article" && references($documentId) && publishAt <= now() && (!defined(unpublishAt) || unpublishAt > now())] | order(publishAt desc) {\n  _id, title, slug, publishAt, featured, tags,\n  "coverImageUrl": coverImage.asset->url + "?w=800&q=80&fm=webp&fit=max"\n}': RELATED_ARTICLES_QUERY_RESULT;
    '*[_type == "article" && slug.current == $slug && publishAt <= now() && (!defined(unpublishAt) || unpublishAt > now())][0] {\n  _id, title, slug, publishAt, featured, tags,\n  "coverImageUrl": coverImage.asset->url + "?w=1200&q=80&fm=webp&fit=max",\n  body[]{ ..., "fileUrl": file.asset->url, "fileSize": file.asset->size, "fileMimeType": file.asset->mimeType, "fileOriginalFilename": file.asset->originalFilename, "asset": select(_type == "image" => asset->{ "url": url + "?w=800&q=80&fm=webp&fit=max" }, _type == "articleImage" => image.asset->{ "url": url + "?w=800&q=80&fm=webp&fit=max" }), markDefs[]{ ..., _type == "internalLink" => { ..., "reference": reference->{ _type, "slug": slug.current, psdId } } } },\n  relatedArticles[]-> { _id, title, slug, publishAt, unpublishAt, "coverImageUrl": coverImage.asset->url + "?w=800&q=80&fm=webp&fit=max" },\n  "mentionedPlayers": body[].markDefs[_type == "internalLink" && reference->_type == "player"].reference-> {\n    _id, firstName, lastName, position,\n    "imageUrl": psdImage.asset->url + "?w=400&q=80&fm=webp&fit=max",\n    psdId\n  },\n  "mentionedTeams": body[].markDefs[_type == "internalLink" && reference->_type == "team"].reference-> {\n    _id, name,\n    "imageUrl": teamImage.asset->url + "?w=400&q=80&fm=webp&fit=max",\n    "slug": slug.current\n  },\n  "mentionedStaffMembers": body[].markDefs[_type == "internalLink" && reference->_type == "staffMember"].reference-> {\n    _id, firstName, lastName, positionTitle,\n    "imageUrl": photo.asset->url + "?w=400&q=80&fm=webp&fit=max"\n  }\n}': ARTICLE_BY_SLUG_QUERY_RESULT;
    '*[_type == "homePage"][0] {\n    "bannerSlotA": bannerSlotA-> {\n      _id,\n      "imageUrl": image.asset->url,\n      alt,\n      href\n    },\n    "bannerSlotB": bannerSlotB-> {\n      _id,\n      "imageUrl": image.asset->url,\n      alt,\n      href\n    },\n    "bannerSlotC": bannerSlotC-> {\n      _id,\n      "imageUrl": image.asset->url,\n      alt,\n      href\n    }\n  }': HOMEPAGE_BANNERS_QUERY_RESULT;
    '*[_type == "player" && archived != true] | order(lastName asc) {\n  _id, psdId, firstName, lastName, jerseyNumber, keeper, positionPsd, position,\n  birthDate, nationality, height, weight,\n  "psdImageUrl": psdImage.asset->url + "?w=400&q=80&fm=webp&fit=max",\n  "transparentImageUrl": transparentImage.asset->url + "?w=600&q=80&fm=webp&fit=max",\n  "celebrationImageUrl": celebrationImage.asset->url + "?w=600&q=80&fm=webp&fit=max",\n  bio\n}': PLAYERS_QUERY_RESULT;
    '*[_type == "player" && psdId == $psdId][0] {\n  _id, psdId, firstName, lastName, jerseyNumber, keeper, positionPsd, position,\n  birthDate, nationality, height, weight,\n  "psdImageUrl": psdImage.asset->url + "?w=400&q=80&fm=webp&fit=max",\n  "transparentImageUrl": transparentImage.asset->url + "?w=600&q=80&fm=webp&fit=max",\n  "celebrationImageUrl": celebrationImage.asset->url + "?w=600&q=80&fm=webp&fit=max",\n  bio\n}': PLAYER_BY_PSD_ID_QUERY_RESULT;
    '*[_type == "sponsor" && active == true] | order(name asc) {\n  _id, name, url, type, tier, featured, "logoUrl": logo.asset->url + "?w=400&q=80&fm=webp&fit=max"\n}': SPONSORS_QUERY_RESULT;
    '*[_type == "staffMember" && archived != true && inOrganigram == true] | order(lastName asc) {\n  _id,\n  firstName,\n  lastName,\n  positionTitle,\n  positionShort,\n  department,\n  email,\n  phone,\n  "photoUrl": photo.asset->url + "?w=200&q=80&fm=webp&fit=max",\n  responsibilities,\n  "parentId": select(defined(parentMember) && parentMember->inOrganigram == true && parentMember->archived != true => parentMember->_id, null)\n}': STAFF_MEMBERS_QUERY_RESULT;
    '*[_type == "team" && archived != true && showInNavigation != false] | order(name asc) {\n  _id, psdId, name, "slug": slug.current, age, gender, footbelId, leagueId, division, divisionFull,\n  tagline,\n  "teamImageUrl": teamImage.asset->url + "?w=1200&q=80&fm=webp&fit=max"\n}': TEAMS_QUERY_RESULT;
    '*[_type == "team" && slug.current == $slug][0] {\n  _id, psdId, name, "slug": slug.current, age, gender, footbelId, leagueId, division, divisionFull,\n  tagline, body[]{ ..., "fileUrl": file.asset->url }, contactInfo,\n  "teamImageUrl": teamImage.asset->url + "?w=1200&q=80&fm=webp&fit=max",\n  trainingSchedule,\n  players[]-> {\n    _id, psdId, firstName, lastName, jerseyNumber, keeper, positionPsd, position,\n    "psdImageUrl": psdImage.asset->url + "?w=400&q=80&fm=webp&fit=max",\n    "transparentImageUrl": transparentImage.asset->url + "?w=600&q=80&fm=webp&fit=max"\n  },\n  staff[]-> { _id, firstName, lastName, role, "photoUrl": photo.asset->url + "?w=200&q=80&fm=webp&fit=max" }\n}': TEAM_BY_SLUG_QUERY_RESULT;
    '*[_type == "team" && archived != true && showInNavigation != false && defined(age)] | order(name asc) {\n  _id, name, "slug": slug.current, age,\n  division, divisionFull, tagline,\n  "teamImageUrl": teamImage.asset->url + "?w=1200&q=80&fm=webp&fit=max",\n  staff[]-> { firstName, lastName, role }\n}': TEAMS_LANDING_QUERY_RESULT;
  }
}
