/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.workerd-test.jsonc --include-runtime=false src/test-helpers/workerd-test-env.d.ts` (hash: ed672e02ed83b21089f82cbc72bbdad7)
interface __BaseEnv_Env {
  PSD_CACHE: KVNamespace;
  PSD_GATE: DurableObjectNamespace<import("./workerd-entry").PsdGate>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./workerd-entry");
    durableNamespaces: "PsdGate";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
